### PR TITLE
Add fluentbit logging support, sending logs to ELK

### PR DESCRIPTION
**Pull request by rhystmills**
## What does this change?

This send our logs to ELK via FluentBit. This is quite simple now that DevX provide FluentBit in their `cdk-base` AMI role. This PR moves to [an ami that include CDK-base](https://amigo.gutools.co.uk/recipes/editorial-tools-focal-java8-ngrams-ARM-cdk-base) and adds the minimal riff-raff changes required to support FluentBit logging. The [commented guidance in the cdk repo](https://github.com/guardian/cdk/blob/9f79cfab8557144d0edc3a20057e2db5bc465906/src/patterns/ec2-app/base.ts#L48) was helpful.

Logs appear in ELK under [`typerighter-rule-manager` and `typerighter-checker`](https://logs.gutools.co.uk/s/editorial-tools/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!f,value:10000),time:(from:now-3M,to:now))&_a=(columns:!(app,message,log),filters:!(),index:'67604290-baa6-11e9-bea2-633437abb232',interval:auto,query:(language:kuery,query:'app.keyword%3Dtyperighter-rule-manager%20OR%20app.keyword%3Dtyperighter-checker'),sort:!(!('@timestamp',desc)))).

I've deployed to CODE and seen logs for the Rule Manager and Checker:

| Logs for Rule Manager | Logs for Checker |
| --- | --- |
| image | image |

## How to test

Deploy to CODE and check [ELK](https://logs.gutools.co.uk/s/editorial-tools/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!f,value:10000),time:(from:now-3M,to:now))&_a=(columns:!(app,message,log),filters:!(),index:'67604290-baa6-11e9-bea2-633437abb232',interval:auto,query:(language:kuery,query:'app.keyword%3Dtyperighter-rule-manager%20OR%20app.keyword%3Dtyperighter-checker'),sort:!(!('@timestamp',desc)))) for Typerighter logs.

### CODE REVIEW

**Comment by jonathonherbert** [comment]
Nice, such a win for gu-cdk! 🎉  

If we're doing this for both apps, let's remove the now-redundant [ELK logging](https://github.com/guardian/typerighter/blob/main/apps/common-lib/src/main/scala/com/gu/typerighter/lib/ElkLogging.scala) from the checker app (and any related dependencies) and verify that checker is still logging – a nice cathartic cleanout 😀

**Comment by rhystmills** [comment]
> 

That's now gone, deployed to CODE and logs for checker were still showing up in ELK.

**Comment by jonathonherbert** [comment]
Nice! We're almost there, I've taken a look at the logs, and I think they're being parsed in a slightly odd way – we're including some meta in the `message` field, and we're missing some logging markers too – compare e.g. [this log entry from `main`](https://logs.gutools.co.uk/s/editorial-tools/app/discover#/doc/67604290-baa6-11e9-bea2-633437abb232/logstash-ed-tools-2023.03.28?id=UQqCKIcB1hyHdy9pKUGp) to one from [this branch.](https://logs.gutools.co.uk/s/editorial-tools/app/discover#/doc/67604290-baa6-11e9-bea2-633437abb232/logstash-ed-tools-2023.03.31?id=RkvcNocBc_V_CELiHSrd)

Suspect it's a formatting thing. Taking a look at another app that uses `applicationLogging`, I wonder if [adding a LogstashEncoder](https://github.com/guardian/amiable/blob/d46478b9b2a82493b2d3f483c871e0a0c9812194/conf/logback.xml#L6) to our stdout appender might help?

**Comment by rhystmills** [comment]
Good spot

> Nice! We're almost there, I've taken a look at the logs, and I think they're being parsed in a slightly odd way – we're including some meta in the `message` field, and we're missing some logging markers too – compare e.g. [this log entry from `main`](https://logs.gutools.co.uk/s/editorial-tools/app/discover#/doc/67604290-baa6-11e9-bea2-633437abb232/logstash-ed-tools-2023.03.28?id=UQqCKIcB1hyHdy9pKUGp) to one from [this branch.](https://logs.gutools.co.uk/s/editorial-tools/app/discover#/doc/67604290-baa6-11e9-bea2-633437abb232/logstash-ed-tools-2023.03.31?id=RkvcNocBc_V_CELiHSrd)
> 
> Suspect it's a formatting thing. Taking a look at another app that uses `applicationLogging`, I wonder if [adding a LogstashEncoder](https://github.com/guardian/amiable/blob/d46478b9b2a82493b2d3f483c871e0a0c9812194/conf/logback.xml#L6) to our stdout appender might help?
> 
> Worth noting that this is not clear from the CDK docs at the moment! Once we've confirmed a fix, it'd be good to update them to make it clear for all users that a given format is expected at the point at which you're setting the flag in CDK.

Good spot Jon, I've updated those `logback.xml` files now - will deploy to CODE and check the logs to see if they're looking right.

**Comment by rhystmills** [comment]
Looking better now with [logs from CODE](https://logs.gutools.co.uk/s/editorial-tools/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!f,value:10000),time:(from:now-3h,to:now))&_a=(columns:!(app,message,log),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'67604290-baa6-11e9-bea2-633437abb232',key:stage,negate:!f,params:(query:CODE),type:phrase),query:(match_phrase:(stage:CODE)))),index:'67604290-baa6-11e9-bea2-633437abb232',interval:auto,query:(language:kuery,query:'app.keyword%3Dtyperighter-rule-manager%20OR%20app.keyword%3Dtyperighter-checker'),sort:!(!('@timestamp',desc)))) including the additional fields:.

**Review by jonathonherbert — APPROVED** [review]
Looks great!

**Pull request merged**
