### PR TITLE
Updates base AMI to focal

### PR DESCRIPTION
**Pull request by ParisaTork**
## What does this change?

Updates base AMI to focal. The recipe has been updated to remove aws-inspector. Please double check the recipe before approving: https://amigo.gutools.co.uk/recipes/editorial-tools-focal-java8-ngrams-ARM

## How to test

Check app functionality and logs are all okay.

## Accessibility

-   [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader)
-   [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#keyboard)
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#contrast)
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-colour)

### CODE REVIEW

**Comment by phillipbarron** [comment]
Shouldn't the base image for this be the ARM one?

**Comment by ParisaTork** [comment]
Great spot - have just updated the recipe to ARM ubuntu-focal :)

**Review by phillipbarron — APPROVED** [review]
Tested in code:

Typerighter appears to be functioning in Composer as expected. There is a (probably unrelated) error in the typerighter-rule-manager logs relating to a 403 when attempting to retrieve permissions from S3.

```
2023-02-14 14:01:01,034 [ERROR] from com.gu.permissions.S3PermissionsProvider in pool-4-thread-1 - Could not refresh permissions from S3
com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: VHCK9YMS4DB6EYZH; S3 Extended Request ID: MbrRtTWNzT/jnyX89pMtEH+17QF7OQeVMKQCppW+f5vl/Z0A5BFQJGi7gaRdYNDYhiFvbeZWA5XESBUIalVYAA==; Proxy: null)
```

Both `typewriter-checker` and `typerighter-rule-manager` report running:

```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal
```

Might be worth verifying that the S3 error exists for main. If so, I'd say this is safe to merge and we should raise a ticket to investigate and resolve the `typerighter-rule-manager` errors.

👍

**Review by jonathonherbert — APPROVED** [review]
Deployed to CODE, works as expected 👍

**Pull request merged**
